version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=dnofre
      - POSTGRES_USER=marie
      - POSTGRES_PASSWORD=56103pBbwj*
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root7182
    ports:
      - '5050:80'
    depends_on:
      - postgres
